# ---
# apiVersion: ceph.rook.io/v1
# metadata:
#   name: nvme-pool-unsafe
#   namespace: rook-ceph
# spec:
#   failureDomain: osd
#   replicated:
#     size: 1
#     requireSafeReplicaSize: false
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: nvme-unsafe
# provisioner: rook-ceph.rbd.csi.ceph.com
# parameters:
#   clusterID: rook-ceph
#   pool: nvme-pool-unsafe
#   imageFormat: "2"
#   imageFeatures: layering

#   # The secrets contain Ceph admin credentials.
#   csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
#   csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
#   csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
#   csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
#   csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
#   csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
#   csi.storage.k8s.io/fstype: ext4

# # Delete the rbd volume when a PVC is deleted
# reclaimPolicy: Retain
# allowVolumeExpansion: true