apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart: rook-ceph
  version: v1.12.1
  sourceRef:
    kind: HelmRepository
    name: rook-charts