# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: rook-ceph
#   namespace: rook-ceph
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: rook-ceph
#       version: v1.11.1
#       interval: 5m
#       sourceRef:
#         kind: HelmRepository
#         name: rook-charts
#         namespace: flux-system