# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: traefik
#   namespace: networking
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: traefik
#       version: v33.2.1
#       sourceRef:
#         kind: HelmRepository
#         name: traefik-charts
#         namespace: flux-system
#       interval: 5m
#   values:
#     deployment:
#       kind: DaemonSet
#     logs:
#       general:
#         level: DEBUG
#     ingressClass:
#       enabled: true
#       isDefaultClass: true
#     ingressRoute:
#       dashboard:
#         enabled: true
#     additionalArguments:
#       - "--ping"
#       #- "--metrics.prometheus=true"
#       - "--api.dashboard=true"
#       - "--entrypoints.websecure.http.tls"
#       - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#       - "--entrypoints.web.http.redirections.entryPoint.to=:443"
#     global:
#       sendAnonymousUsage: false
#     providers:
#       kubernetesIngress:
#         publishedService:
#           enabled: true